app = "shodoukan-api"
primary_region = "cdg"

[build]
  dockerfile = "packages/shodoukan-api/Dockerfile"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0

  [[http_service.checks]]
    grace_period = "15s"
    interval = "30s"
    method = "GET"
    path = "/openapi.json"
    timeout = "10s"

[[vm]]
  size = "shared-cpu-1x"
  memory = "256mb"
