"""Create initial schema

Revision ID: 4ea69ccc76fd
Revises:
Create Date: 2026-10-01 22:53:46.067445+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "4ea69ccc76fd"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("username", sa.String(length=255), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
    )
    op.create_table(
        "entry_collections",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_entry_collections_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_entry_collections")),
        sa.UniqueConstraint(
            "user_id", "name", name=op.f("uq_entry_collections_user_id_name")
        ),
    )
    op.create_index(
        op.f("ix_entry_collections_user_id"),
        "entry_collections",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "kanji_collections",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_kanji_collections_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_kanji_collections")),
        sa.UniqueConstraint(
            "user_id", "name", name=op.f("uq_kanji_collections_user_id_name")
        ),
    )
    op.create_index(
        op.f("ix_kanji_collections_user_id"),
        "kanji_collections",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "practice_entries",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("source_entry_id", sa.Integer(), nullable=False),
        sa.Column("jlpt", sa.Integer(), nullable=True),
        sa.Column("is_common", sa.Boolean(), nullable=False),
        sa.Column(
            "is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_practice_entries_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_practice_entries")),
        sa.UniqueConstraint(
            "user_id",
            "source_entry_id",
            name=op.f("uq_practice_entries_user_id_source_entry_id"),
        ),
    )
    op.create_index(
        op.f("ix_practice_entries_user_id"),
        "practice_entries",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "practice_kanji",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("literal", sa.String(length=8), nullable=False),
        sa.Column("grade", sa.Integer(), nullable=True),
        sa.Column("stroke_count", sa.Integer(), nullable=False),
        sa.Column("freq", sa.Integer(), nullable=True),
        sa.Column("jlpt", sa.Integer(), nullable=True),
        sa.Column(
            "is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_practice_kanji_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_practice_kanji")),
        sa.UniqueConstraint(
            "user_id", "literal", name=op.f("uq_practice_kanji_user_id_literal")
        ),
    )
    op.create_index(
        op.f("ix_practice_kanji_user_id"), "practice_kanji", ["user_id"], unique=False
    )
    op.create_table(
        "entry_collection_items",
        sa.Column("collection_id", sa.Integer(), nullable=False),
        sa.Column("entry_id", sa.Integer(), nullable=False),
        sa.Column("added_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["collection_id"],
            ["entry_collections.id"],
            name=op.f("fk_entry_collection_items_collection_id_entry_collections"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["entry_id"],
            ["practice_entries.id"],
            name=op.f("fk_entry_collection_items_entry_id_practice_entries"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "collection_id", "entry_id", name=op.f("pk_entry_collection_items")
        ),
    )
    op.create_index(
        op.f("ix_entry_collection_items_entry_id"),
        "entry_collection_items",
        ["entry_id"],
        unique=False,
    )
    op.create_table(
        "kanji_collection_items",
        sa.Column("collection_id", sa.Integer(), nullable=False),
        sa.Column("kanji_id", sa.Integer(), nullable=False),
        sa.Column("added_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["collection_id"],
            ["kanji_collections.id"],
            name=op.f("fk_kanji_collection_items_collection_id_kanji_collections"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["kanji_id"],
            ["practice_kanji.id"],
            name=op.f("fk_kanji_collection_items_kanji_id_practice_kanji"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "collection_id", "kanji_id", name=op.f("pk_kanji_collection_items")
        ),
    )
    op.create_index(
        op.f("ix_kanji_collection_items_kanji_id"),
        "kanji_collection_items",
        ["kanji_id"],
        unique=False,
    )
    op.create_table(
        "practice_entry_kanji_readings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("entry_id", sa.Integer(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("kanji", sa.String(), nullable=False),
        sa.Column("info", sa.JSON(), nullable=False),
        sa.Column(
            "enabled", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["entry_id"],
            ["practice_entries.id"],
            name=op.f("fk_practice_entry_kanji_readings_entry_id_practice_entries"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_practice_entry_kanji_readings")),
    )
    op.create_index(
        op.f("ix_practice_entry_kanji_readings_entry_id"),
        "practice_entry_kanji_readings",
        ["entry_id"],
        unique=False,
    )
    op.create_table(
        "practice_entry_readings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("entry_id", sa.Integer(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("text", sa.String(), nullable=False),
        sa.Column("no_kanji", sa.Boolean(), nullable=False),
        sa.Column("info", sa.JSON(), nullable=False),
        sa.Column("restricted_to", sa.JSON(), nullable=False),
        sa.Column(
            "enabled", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["entry_id"],
            ["practice_entries.id"],
            name=op.f("fk_practice_entry_readings_entry_id_practice_entries"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_practice_entry_readings")),
    )
    op.create_index(
        op.f("ix_practice_entry_readings_entry_id"),
        "practice_entry_readings",
        ["entry_id"],
        unique=False,
    )
    op.create_table(
        "practice_kanji_meanings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("kanji_id", sa.Integer(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("text", sa.String(), nullable=False),
        sa.Column("lang", sa.String(length=8), nullable=False),
        sa.Column(
            "enabled", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        sa.Column(
            "origin", sa.String(length=16), server_default="imported", nullable=False
        ),
        sa.CheckConstraint(
            "origin IN ('imported', 'added')",
            name=op.f("ck_practice_kanji_meanings_origin"),
        ),
        sa.ForeignKeyConstraint(
            ["kanji_id"],
            ["practice_kanji.id"],
            name=op.f("fk_practice_kanji_meanings_kanji_id_practice_kanji"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_practice_kanji_meanings")),
    )
    op.create_index(
        op.f("ix_practice_kanji_meanings_kanji_id"),
        "practice_kanji_meanings",
        ["kanji_id"],
        unique=False,
    )
    op.create_table(
        "practice_kanji_reading_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("kanji_id", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(length=8), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("text", sa.String(), nullable=False),
        sa.Column(
            "enabled", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        sa.CheckConstraint(
            "kind IN ('on', 'kun', 'nanori')",
            name=op.f("ck_practice_kanji_reading_items_kind"),
        ),
        sa.ForeignKeyConstraint(
            ["kanji_id"],
            ["practice_kanji.id"],
            name=op.f("fk_practice_kanji_reading_items_kanji_id_practice_kanji"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_practice_kanji_reading_items")),
    )
    op.create_index(
        op.f("ix_practice_kanji_reading_items_kanji_id"),
        "practice_kanji_reading_items",
        ["kanji_id"],
        unique=False,
    )
    op.create_table(
        "practice_senses",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("entry_id", sa.Integer(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("pos", sa.JSON(), nullable=False),
        sa.Column("misc", sa.JSON(), nullable=False),
        sa.Column("dialects", sa.JSON(), nullable=False),
        sa.Column("info", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["entry_id"],
            ["practice_entries.id"],
            name=op.f("fk_practice_senses_entry_id_practice_entries"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_practice_senses")),
    )
    op.create_index(
        op.f("ix_practice_senses_entry_id"),
        "practice_senses",
        ["entry_id"],
        unique=False,
    )
    op.create_table(
        "practice_examples",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("sense_id", sa.Integer(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("text", sa.String(), nullable=False),
        sa.Column(
            "enabled", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        sa.Column(
            "origin", sa.String(length=16), server_default="imported", nullable=False
        ),
        sa.CheckConstraint(
            "origin IN ('imported', 'added')", name=op.f("ck_practice_examples_origin")
        ),
        sa.ForeignKeyConstraint(
            ["sense_id"],
            ["practice_senses.id"],
            name=op.f("fk_practice_examples_sense_id_practice_senses"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_practice_examples")),
    )
    op.create_index(
        op.f("ix_practice_examples_sense_id"),
        "practice_examples",
        ["sense_id"],
        unique=False,
    )
    op.create_table(
        "practice_glosses",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("sense_id", sa.Integer(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("text", sa.String(), nullable=False),
        sa.Column("lang", sa.String(length=8), nullable=False),
        sa.Column("type", sa.String(), nullable=True),
        sa.Column(
            "enabled", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        sa.Column(
            "origin", sa.String(length=16), server_default="imported", nullable=False
        ),
        sa.CheckConstraint(
            "origin IN ('imported', 'added')", name=op.f("ck_practice_glosses_origin")
        ),
        sa.ForeignKeyConstraint(
            ["sense_id"],
            ["practice_senses.id"],
            name=op.f("fk_practice_glosses_sense_id_practice_senses"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_practice_glosses")),
    )
    op.create_index(
        op.f("ix_practice_glosses_sense_id"),
        "practice_glosses",
        ["sense_id"],
        unique=False,
    )
    op.create_table(
        "practice_example_sentences",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("example_id", sa.Integer(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("lang", sa.String(length=8), nullable=False),
        sa.Column("text", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["example_id"],
            ["practice_examples.id"],
            name=op.f("fk_practice_example_sentences_example_id_practice_examples"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_practice_example_sentences")),
    )
    op.create_index(
        op.f("ix_practice_example_sentences_example_id"),
        "practice_example_sentences",
        ["example_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_practice_example_sentences_example_id"),
        table_name="practice_example_sentences",
    )
    op.drop_table("practice_example_sentences")
    op.drop_index(op.f("ix_practice_glosses_sense_id"), table_name="practice_glosses")
    op.drop_table("practice_glosses")
    op.drop_index(op.f("ix_practice_examples_sense_id"), table_name="practice_examples")
    op.drop_table("practice_examples")
    op.drop_index(op.f("ix_practice_senses_entry_id"), table_name="practice_senses")
    op.drop_table("practice_senses")
    op.drop_index(
        op.f("ix_practice_kanji_reading_items_kanji_id"),
        table_name="practice_kanji_reading_items",
    )
    op.drop_table("practice_kanji_reading_items")
    op.drop_index(
        op.f("ix_practice_kanji_meanings_kanji_id"),
        table_name="practice_kanji_meanings",
    )
    op.drop_table("practice_kanji_meanings")
    op.drop_index(
        op.f("ix_practice_entry_readings_entry_id"),
        table_name="practice_entry_readings",
    )
    op.drop_table("practice_entry_readings")
    op.drop_index(
        op.f("ix_practice_entry_kanji_readings_entry_id"),
        table_name="practice_entry_kanji_readings",
    )
    op.drop_table("practice_entry_kanji_readings")
    op.drop_index(
        op.f("ix_kanji_collection_items_kanji_id"), table_name="kanji_collection_items"
    )
    op.drop_table("kanji_collection_items")
    op.drop_index(
        op.f("ix_entry_collection_items_entry_id"), table_name="entry_collection_items"
    )
    op.drop_table("entry_collection_items")
    op.drop_index(op.f("ix_practice_kanji_user_id"), table_name="practice_kanji")
    op.drop_table("practice_kanji")
    op.drop_index(op.f("ix_practice_entries_user_id"), table_name="practice_entries")
    op.drop_table("practice_entries")
    op.drop_index(op.f("ix_kanji_collections_user_id"), table_name="kanji_collections")
    op.drop_table("kanji_collections")
    op.drop_index(op.f("ix_entry_collections_user_id"), table_name="entry_collections")
    op.drop_table("entry_collections")
    op.drop_table("users")
    # ### end Alembic commands ###
