"""Write use cases, one module per subject."""

from .collection_commands import (
    AddEntryToCollection,
    AddKanjiToCollection,
    CreateEntryCollection,
    CreateKanjiCollection,
    DeleteEntryCollection,
    DeleteKanjiCollection,
    RemoveEntryFromCollection,
    RemoveKanjiFromCollection,
    UpdateEntryCollection,
    UpdateKanjiCollection,
)
from .exercise_commands import CreateExercise, DeleteExercise, UpdateExercise
from .exercise_session_commands import (
    AnswerExerciseQuestion,
    FinishExerciseSession,
    StartExerciseSession,
)
from .library_commands import ImportEntry, ImportKanji, ImportResult
from .practice_entry_commands import (
    AddEntryExample,
    AddEntryGloss,
    AddEntrySense,
    EditEntryExample,
    EditEntryGloss,
    RemoveEntryExample,
    RemoveEntryFromLibrary,
    RemoveEntryGloss,
    RemoveEntrySense,
    SetEntryActive,
    SetEntryNotes,
    SetEntryPartEnabled,
    SetSenseNotes,
)
from .practice_kanji_commands import (
    AddKanjiMeaning,
    EditKanjiMeaning,
    RemoveKanjiFromLibrary,
    RemoveKanjiMeaning,
    SetKanjiActive,
    SetKanjiNotes,
    SetKanjiPartEnabled,
)
from .user_commands import EnsureUser

__all__ = [
    "AddEntryExample",
    "AddEntryGloss",
    "AddEntrySense",
    "AddEntryToCollection",
    "AddKanjiMeaning",
    "AddKanjiToCollection",
    "AnswerExerciseQuestion",
    "CreateEntryCollection",
    "CreateExercise",
    "CreateKanjiCollection",
    "DeleteEntryCollection",
    "DeleteExercise",
    "DeleteKanjiCollection",
    "EditEntryExample",
    "EditEntryGloss",
    "EditKanjiMeaning",
    "EnsureUser",
    "FinishExerciseSession",
    "ImportEntry",
    "ImportKanji",
    "ImportResult",
    "RemoveEntryExample",
    "RemoveEntryFromCollection",
    "RemoveEntryFromLibrary",
    "RemoveEntryGloss",
    "RemoveEntrySense",
    "RemoveKanjiFromCollection",
    "RemoveKanjiFromLibrary",
    "RemoveKanjiMeaning",
    "SetEntryActive",
    "SetEntryNotes",
    "SetEntryPartEnabled",
    "SetKanjiActive",
    "SetKanjiNotes",
    "SetKanjiPartEnabled",
    "SetSenseNotes",
    "StartExerciseSession",
    "UpdateEntryCollection",
    "UpdateExercise",
    "UpdateKanjiCollection",
]
